<?php

namespace Database\Seeders;

use App\Models\Muzakki;
use Illuminate\Database\Seeder;

class MuzakkiSeeder extends Seeder
{
    public function run(): void
    {
        $muzakkiData = [
            // Dosen / Staf Civitas UNSIL
            [
                'nama'           => 'Dr. Ahmad Fauzi, M.Pd.',
                'nik'            => '3278011203750001',
                'nip'            => '197503122001121001',
                'jenis_kelamin'  => 'Laki-laki',
                'tempat_lahir'   => 'Tasikmalaya',
                'tanggal_lahir'  => '1975-03-12',
                'pekerjaan'      => 'Dosen Lektor Kepala',
                'alamat_lengkap' => 'Jl. BKR No. 45, Kahuripan, Tawang, Kota Tasikmalaya',
                'email'          => 'ahmadpauzi@unsil.ac.id',
                'no_hp'          => '08111000001',
                'kategori'       => 'Dosen & Staf UNSIL',
                'unit_kerja'     => 'Fakultas Keguruan dan Ilmu Pendidikan (FKIP) · Pendidikan Matematika',
            ],
            [
                'nama'           => 'Prof. Siti Rahayu, Ph.D.',
                'nik'            => '3278026508680002',
                'nip'            => '196808251994032002',
                'jenis_kelamin'  => 'Perempuan',
                'tempat_lahir'   => 'Bandung',
                'tanggal_lahir'  => '1968-08-25',
                'pekerjaan'      => 'Guru Besar / Dosen',
                'alamat_lengkap' => 'Komplek Unsil Permai No. 12, Cihideung, Kota Tasikmalaya',
                'email'          => 'sitirahayu@unsil.ac.id',
                'no_hp'          => '08111000002',
                'kategori'       => 'Dosen & Staf UNSIL',
                'unit_kerja'     => 'Fakultas Ekonomi dan Bisnis · Manajemen',
            ],
            [
                'nama'           => 'Drs. Hendra Kusuma, M.Si.',
                'nik'            => '3278011005700003',
                'nip'            => '197005101998021003',
                'jenis_kelamin'  => 'Laki-laki',
                'tempat_lahir'   => 'Ciamis',
                'tanggal_lahir'  => '1970-05-10',
                'pekerjaan'      => 'Dosen Lektor',
                'alamat_lengkap' => 'Jl. Sutisna Senjaya No. 88, Cibeureum, Kota Tasikmalaya',
                'email'          => 'hendrak@unsil.ac.id',
                'no_hp'          => '08111000003',
                'kategori'       => 'Dosen & Staf UNSIL',
                'unit_kerja'     => 'Fakultas Ilmu Sosial dan Ilmu Politik (FISIP) · Hukum Bisnis',
            ],
            [
                'nama'           => 'Ir. Budi Santoso, M.T.',
                'nik'            => '3278011511720004',
                'nip'            => '197211152000121004',
                'jenis_kelamin'  => 'Laki-laki',
                'tempat_lahir'   => 'Garut',
                'tanggal_lahir'  => '1972-11-15',
                'pekerjaan'      => 'Dosen Lektor',
                'alamat_lengkap' => 'Jl. Siliwangi Perum Bumi Asri B-3, Tawang, Kota Tasikmalaya',
                'email'          => 'budisantoso@unsil.ac.id',
                'no_hp'          => '08111000004',
                'kategori'       => 'Dosen & Staf UNSIL',
                'unit_kerja'     => 'Fakultas Teknik · Teknik Sipil',
            ],
            [
                'nama'           => 'Dr. Dewi Lestari, M.Kes.',
                'nik'            => '3278026004810005',
                'nip'            => '198104202008012005',
                'jenis_kelamin'  => 'Perempuan',
                'tempat_lahir'   => 'Tasikmalaya',
                'tanggal_lahir'  => '1981-04-20',
                'pekerjaan'      => 'Dosen Lektor',
                'alamat_lengkap' => 'Jl. Letjen Mashudi No. 102, Tamansari, Kota Tasikmalaya',
                'email'          => 'dewilestari@unsil.ac.id',
                'no_hp'          => '08111000005',
                'kategori'       => 'Dosen & Staf UNSIL',
                'unit_kerja'     => 'Fakultas Ilmu Kesehatan · Kesehatan Masyarakat',
            ],
            [
                'nama'           => 'Dra. Ratna Wijaya, M.Pd.',
                'nik'            => '3278025809730006',
                'nip'            => '197309181999032006',
                'jenis_kelamin'  => 'Perempuan',
                'tempat_lahir'   => 'Sumedang',
                'tanggal_lahir'  => '1973-09-18',
                'pekerjaan'      => 'Dosen Lektor',
                'alamat_lengkap' => 'Jl. RE Martadinata No. 55, Cipedes, Kota Tasikmalaya',
                'email'          => 'ratnaw@unsil.ac.id',
                'no_hp'          => '08111000006',
                'kategori'       => 'Dosen & Staf UNSIL',
                'unit_kerja'     => 'Fakultas Keguruan dan Ilmu Pendidikan (FKIP) · Pendidikan Bahasa Indonesia',
            ],
            [
                'nama'           => 'H. Supriadi, S.E., M.M.',
                'nik'            => '3278010502760007',
                'nip'            => '197602052003121007',
                'jenis_kelamin'  => 'Laki-laki',
                'tempat_lahir'   => 'Tasikmalaya',
                'tanggal_lahir'  => '1976-02-05',
                'pekerjaan'      => 'Dosen Lektor Kepala',
                'alamat_lengkap' => 'Jl. Dr. Moch. Hatta No. 71, Cipedes, Kota Tasikmalaya',
                'email'          => 'supriadi@unsil.ac.id',
                'no_hp'          => '08111000007',
                'kategori'       => 'Dosen & Staf UNSIL',
                'unit_kerja'     => 'Fakultas Ekonomi dan Bisnis · Akuntansi',
            ],
            [
                'nama'           => 'Dr. Rina Marlina, M.Si.',
                'nik'            => '3278025407820008',
                'nip'            => '198207142009122008',
                'jenis_kelamin'  => 'Perempuan',
                'tempat_lahir'   => 'Bogor',
                'tanggal_lahir'  => '1982-07-14',
                'pekerjaan'      => 'Dosen Lektor',
                'alamat_lengkap' => 'Perum Graha Persada No. 19, Kawalu, Kota Tasikmalaya',
                'email'          => 'rinamarlin@unsil.ac.id',
                'no_hp'          => '08111000008',
                'kategori'       => 'Dosen & Staf UNSIL',
                'unit_kerja'     => 'Fakultas Pertanian · Agroteknologi',
            ],
            [
                'nama'           => 'Dr. Indra Permana, M.Kom.',
                'nik'            => '3278013001850009',
                'nip'            => '198501302012121009',
                'jenis_kelamin'  => 'Laki-laki',
                'tempat_lahir'   => 'Tasikmalaya',
                'tanggal_lahir'  => '1985-01-30',
                'pekerjaan'      => 'Dosen Lektor',
                'alamat_lengkap' => 'Jl. Tentara Pelajar No. 24, Empangsari, Tawang, Kota Tasikmalaya',
                'email'          => 'indrapermana@unsil.ac.id',
                'no_hp'          => '08111000009',
                'kategori'       => 'Dosen & Staf UNSIL',
                'unit_kerja'     => 'Fakultas Teknik · Informatika',
            ],
            [
                'nama'           => 'Hj. Sari Kusumadewi, S.Pd.',
                'nik'            => '3278025112800010',
                'nip'            => '198012112006042010',
                'jenis_kelamin'  => 'Perempuan',
                'tempat_lahir'   => 'Bandung',
                'tanggal_lahir'  => '1980-12-11',
                'pekerjaan'      => 'Tenaga Kependidikan / Staf',
                'alamat_lengkap' => 'Jl. Sukalaya I No. 14, Cihideung, Kota Tasikmalaya',
                'email'          => 'sarikusu@unsil.ac.id',
                'no_hp'          => '08111000010',
                'kategori'       => 'Dosen & Staf UNSIL',
                'unit_kerja'     => 'Fakultas Keguruan dan Ilmu Pendidikan (FKIP) · Pendidikan Biologi',
            ],
            [
                'nama'           => 'Prof. Bambang Wijaya, Ph.D.',
                'nik'            => '3278010304650011',
                'nip'            => '196504031990031011',
                'jenis_kelamin'  => 'Laki-laki',
                'tempat_lahir'   => 'Yogyakarta',
                'tanggal_lahir'  => '1965-04-03',
                'pekerjaan'      => 'Guru Besar / Dosen',
                'alamat_lengkap' => 'Perumahan Mitra Batik Blok C-8, Indihiang, Kota Tasikmalaya',
                'email'          => 'bambangw@unsil.ac.id',
                'no_hp'          => '08111000011',
                'kategori'       => 'Dosen & Staf UNSIL',
                'unit_kerja'     => 'Fakultas Ekonomi dan Bisnis · Ekonomi Pembangunan',
            ],
            [
                'nama'           => 'Dra. Nani Suryani, M.Pd.',
                'nik'            => '3278026206740012',
                'nip'            => '197406222000032012',
                'jenis_kelamin'  => 'Perempuan',
                'tempat_lahir'   => 'Tasikmalaya',
                'tanggal_lahir'  => '1974-06-22',
                'pekerjaan'      => 'Dosen Lektor',
                'alamat_lengkap' => 'Jl. Paseh No. 33, Tuguraja, Cihideung, Kota Tasikmalaya',
                'email'          => 'nanisury@unsil.ac.id',
                'no_hp'          => '08111000012',
                'kategori'       => 'Dosen & Staf UNSIL',
                'unit_kerja'     => 'Fakultas Keguruan dan Ilmu Pendidikan (FKIP) · Pendidikan Sejarah',
            ],
            [
                'nama'           => 'Dr. Fajar Nugraha, M.T.',
                'nik'            => '3278010810830013',
                'nip'            => '198310082010121013',
                'jenis_kelamin'  => 'Laki-laki',
                'tempat_lahir'   => 'Bandung',
                'tanggal_lahir'  => '1983-10-08',
                'pekerjaan'      => 'Dosen Lektor',
                'alamat_lengkap' => 'Jl. Cisalak No. 20, Sukamanah, Cipedes, Kota Tasikmalaya',
                'email'          => 'fajarnug@unsil.ac.id',
                'no_hp'          => '08111000013',
                'kategori'       => 'Dosen & Staf UNSIL',
                'unit_kerja'     => 'Fakultas Teknik · Teknik Elektro',
            ],
            [
                'nama'           => 'Ir. Yuli Ratnasari, M.P.',
                'nik'            => '3278025705780014',
                'nip'            => '197805172005012014',
                'jenis_kelamin'  => 'Perempuan',
                'tempat_lahir'   => 'Ciamis',
                'tanggal_lahir'  => '1978-05-17',
                'pekerjaan'      => 'Dosen Lektor',
                'alamat_lengkap' => 'Jl. Cineam No. 05, Manonjaya, Kab. Tasikmalaya',
                'email'          => 'yuliratn@unsil.ac.id',
                'no_hp'          => '08111000014',
                'kategori'       => 'Dosen & Staf UNSIL',
                'unit_kerja'     => 'Fakultas Pertanian · Agribisnis',
            ],
            [
                'nama'           => 'Dr. Asep Hermawan, M.Ag.',
                'nik'            => '3278012911770015',
                'nip'            => '197711292003121015',
                'jenis_kelamin'  => 'Laki-laki',
                'tempat_lahir'   => 'Tasikmalaya',
                'tanggal_lahir'  => '1977-11-29',
                'pekerjaan'      => 'Dosen Lektor',
                'alamat_lengkap' => 'Jl. Noenoeng Tisnasaputra No. 18, Kahuripan, Tawang, Kota Tasikmalaya',
                'email'          => 'asepherm@unsil.ac.id',
                'no_hp'          => '08111000015',
                'kategori'       => 'Dosen & Staf UNSIL',
                'unit_kerja'     => 'Fakultas Agama Islam · Ekonomi Syariah',
            ],
            [
                'nama'           => 'Drs. Cecep Saepulloh, M.Si.',
                'nik'            => '3278011403710016',
                'nip'            => '197103141997021016',
                'jenis_kelamin'  => 'Laki-laki',
                'tempat_lahir'   => 'Garut',
                'tanggal_lahir'  => '1971-03-14',
                'pekerjaan'      => 'Dosen Lektor',
                'alamat_lengkap' => 'Jl. Tarumanagara No. 40, Tawangsari, Tawang, Kota Tasikmalaya',
                'email'          => 'cecepsaep@unsil.ac.id',
                'no_hp'          => '08111000016',
                'kategori'       => 'Dosen & Staf UNSIL',
                'unit_kerja'     => 'Fakultas Ilmu Sosial dan Ilmu Politik (FISIP) · Ilmu Politik',
            ],
            [
                'nama'           => 'Dr. Fitri Handayani, M.Gz.',
                'nik'            => '3278024209860017',
                'nip'            => '198609022014022017',
                'jenis_kelamin'  => 'Perempuan',
                'tempat_lahir'   => 'Jakarta',
                'tanggal_lahir'  => '1986-09-02',
                'pekerjaan'      => 'Dosen Lektor',
                'alamat_lengkap' => 'Perumahan Grand Mutiara Blok A-1, Kawalu, Kota Tasikmalaya',
                'email'          => 'fitrih@unsil.ac.id',
                'no_hp'          => '08111000017',
                'kategori'       => 'Dosen & Staf UNSIL',
                'unit_kerja'     => 'Fakultas Ilmu Kesehatan · Gizi',
            ],
            [
                'nama'           => 'M. Rizki Fauzan, S.Kom., M.T.',
                'nik'            => '3278010412890018',
                'nip'            => '198912042018011018',
                'jenis_kelamin'  => 'Laki-laki',
                'tempat_lahir'   => 'Bandung',
                'tanggal_lahir'  => '1989-12-04',
                'pekerjaan'      => 'Dosen Asisten Ahli',
                'alamat_lengkap' => 'Jl. Letnan Harun No. 90, Sukarindik, Bungursari, Kota Tasikmalaya',
                'email'          => 'rizkif@unsil.ac.id',
                'no_hp'          => '08111000018',
                'kategori'       => 'Dosen & Staf UNSIL',
                'unit_kerja'     => 'Fakultas Teknik · Sistem Informasi',
            ],
            [
                'nama'           => 'Dr. Lina Nurhayati, M.Pd.',
                'nik'            => '3278026501790019',
                'nip'            => '197901252005012019',
                'jenis_kelamin'  => 'Perempuan',
                'tempat_lahir'   => 'Tasikmalaya',
                'tanggal_lahir'  => '1979-01-25',
                'pekerjaan'      => 'Dosen Lektor Kepala',
                'alamat_lengkap' => 'Jl. Cipedes I No. 08, Cipedes, Kota Tasikmalaya',
                'email'          => 'linanurh@unsil.ac.id',
                'no_hp'          => '08111000019',
                'kategori'       => 'Dosen & Staf UNSIL',
                'unit_kerja'     => 'Fakultas Keguruan dan Ilmu Pendidikan (FKIP) · Pendidikan Bahasa Inggris',
            ],
            [
                'nama'           => 'Drs. Wahyu Setiawan, M.M.',
                'nik'            => '3278011908720020',
                'nip'            => '197208191998031020',
                'jenis_kelamin'  => 'Laki-laki',
                'tempat_lahir'   => 'Cirebon',
                'tanggal_lahir'  => '1972-08-19',
                'pekerjaan'      => 'Dosen Lektor Kepala',
                'alamat_lengkap' => 'Jl. Gunung Sabeulah No. 34, Argasari, Cihideung, Kota Tasikmalaya',
                'email'          => 'wahyuset@unsil.ac.id',
                'no_hp'          => '08111000020',
                'kategori'       => 'Dosen & Staf UNSIL',
                'unit_kerja'     => 'Fakultas Ekonomi dan Bisnis · Perbankan dan Keuangan Digital (D4)',
            ],

            // Masyarakat Umum
            [
                'nama'           => 'Rd. Andrian Saputra',
                'nik'            => '3278011204850001',
                'nip'            => null,
                'jenis_kelamin'  => 'Laki-laki',
                'tempat_lahir'   => 'Tasikmalaya',
                'tanggal_lahir'  => '1985-04-12',
                'pekerjaan'      => 'Wiraswasta',
                'alamat_lengkap' => 'Jl. HZ Mustofa No. 120, Nagarawangi, Cihideung, Kota Tasikmalaya',
                'email'          => 'andrian.saputra@gmail.com',
                'no_hp'          => '08222000001',
                'kategori'       => 'Muzakki Umum',
                'unit_kerja'     => 'Masyarakat Umum',
            ],
            [
                'nama'           => 'Fitriani Dewi',
                'nik'            => '3278025508900002',
                'nip'            => null,
                'jenis_kelamin'  => 'Perempuan',
                'tempat_lahir'   => 'Bandung',
                'tanggal_lahir'  => '1990-08-15',
                'pekerjaan'      => 'Apoteker / Swasta',
                'alamat_lengkap' => 'Jl. Cieunteung No. 78, Argasari, Cihideung, Kota Tasikmalaya',
                'email'          => 'fitridewi@gmail.com',
                'no_hp'          => '08222000002',
                'kategori'       => 'Muzakki Umum',
                'unit_kerja'     => 'Masyarakat Umum',
            ],
            [
                'nama'           => 'H. Maman Abdurrahman',
                'nik'            => '3278010107720003',
                'nip'            => null,
                'jenis_kelamin'  => 'Laki-laki',
                'tempat_lahir'   => 'Tasikmalaya',
                'tanggal_lahir'  => '1972-07-01',
                'pekerjaan'      => 'Pengusaha Konveksi',
                'alamat_lengkap' => 'Jl. Perintis Kemerdekaan No. 200, Sambongjaya, Mangkubumi, Kota Tasikmalaya',
                'email'          => 'h.maman.abdurrahman@yahoo.com',
                'no_hp'          => '08222000003',
                'kategori'       => 'Muzakki Umum',
                'unit_kerja'     => 'Masyarakat Umum',
            ],
            [
                'nama'           => 'Yeni Susanti',
                'nik'            => '3278036011920004',
                'nip'            => null,
                'jenis_kelamin'  => 'Perempuan',
                'tempat_lahir'   => 'Garut',
                'tanggal_lahir'  => '1992-11-20',
                'pekerjaan'      => 'Pegawai BUMN',
                'alamat_lengkap' => 'Perum Bumi Resik Panglayungan Blok D-15, Cipedes, Kota Tasikmalaya',
                'email'          => 'yenisus@gmail.com',
                'no_hp'          => '08222000004',
                'kategori'       => 'Muzakki Umum',
                'unit_kerja'     => 'Masyarakat Umum',
            ],
            [
                'nama'           => 'Dani Firmansyah',
                'nik'            => '3278011909880005',
                'nip'            => null,
                'jenis_kelamin'  => 'Laki-laki',
                'tempat_lahir'   => 'Tasikmalaya',
                'tanggal_lahir'  => '1988-09-19',
                'pekerjaan'      => 'Konsultan IT',
                'alamat_lengkap' => 'Jl. Ir. H. Juanda No. 88, Panyingkiran, Indihiang, Kota Tasikmalaya',
                'email'          => 'danifirmansyah@outlook.com',
                'no_hp'          => '08222000005',
                'kategori'       => 'Muzakki Umum',
                'unit_kerja'     => 'Masyarakat Umum',
            ],
        ];

        foreach ($muzakkiData as $data) {
            Muzakki::updateOrCreate(
                ['nama' => $data['nama']],
                $data
            );
        }

    }
}

