<?php

namespace Database\Seeders;

use App\Models\Muzakki;
use Illuminate\Database\Seeder;

class MuzakkiSeeder extends Seeder
{
    public function run(): void
    {
        $muzakkiData = [
            // =========================================================================
            // 1. DOSEN & STAF UNSIL (DENGAN KESEPAKATAN ZAKAT REALISTIS)
            // =========================================================================
            [
                'nama'              => 'Dr. Ahmad Fauzi, M.Pd.',
                'nik'               => '3278011203750001',
                'nip'               => '197503122001121001',
                'jenis_kelamin'     => 'Laki-laki',
                'tempat_lahir'      => 'Tasikmalaya',
                'tanggal_lahir'     => '1975-03-12',
                'pekerjaan'         => 'Dosen Lektor Kepala',
                'alamat_lengkap'    => 'Jl. BKR No. 45, Kahuripan, Tawang, Kota Tasikmalaya',
                'email'             => 'ahmadpauzi@unsil.ac.id',
                'no_hp'             => '08111000001',
                'kategori'          => 'Dosen & Staf UNSIL',
                'unit_kerja'        => 'Fakultas Keguruan dan Ilmu Pendidikan (FKIP) · Pendidikan Matematika',
                'jenis_zakat'       => 'Zakat Penghasilan, Zakat Fitrah',
                'frekuensi'         => 'multi-frekuensi',
                'nominal'           => 680000,
                'metode_pembayaran' => 'transfer-bank',
                'pilihan_bank'      => 'BSI',
                'pilihan_ewallet'   => null,
                'kesepakatan_zakat' => [
                    [
                        'key'       => 'penghasilan',
                        'jenis'     => 'Zakat Penghasilan',
                        'frekuensi' => 'bulanan',
                        'nominal'   => 500000,
                        'detail'    => 'Per bulan (Gaji Pokok & Remunerasi)',
                    ],
                    [
                        'key'              => 'fitrah',
                        'jenis'            => 'Zakat Fitrah',
                        'frekuensi'        => 'ramadan',
                        'jumlah_jiwa'      => 4,
                        'nominal_per_jiwa' => 45000,
                        'nominal'          => 180000,
                        'detail'           => '4 Jiwa × Rp 45.000',
                    ],
                ],
            ],
            [
                'nama'              => 'Prof. Siti Rahayu, Ph.D.',
                'nik'               => '3278026508680002',
                'nip'               => '196808251994032002',
                'jenis_kelamin'     => 'Perempuan',
                'tempat_lahir'      => 'Bandung',
                'tanggal_lahir'     => '1968-08-25',
                'pekerjaan'         => 'Guru Besar / Dosen',
                'alamat_lengkap'    => 'Komplek Unsil Permai No. 12, Cihideung, Kota Tasikmalaya',
                'email'             => 'sitirahayu@unsil.ac.id',
                'no_hp'             => '08111000002',
                'kategori'          => 'Dosen & Staf UNSIL',
                'unit_kerja'        => 'Fakultas Ekonomi dan Bisnis · Manajemen',
                'jenis_zakat'       => 'Zakat Penghasilan, Zakat Maal',
                'frekuensi'         => 'multi-frekuensi',
                'nominal'           => 3500000,
                'metode_pembayaran' => 'transfer-bank',
                'pilihan_bank'      => 'Mandiri',
                'pilihan_ewallet'   => null,
                'kesepakatan_zakat' => [
                    [
                        'key'       => 'penghasilan',
                        'jenis'     => 'Zakat Penghasilan',
                        'frekuensi' => 'bulanan',
                        'nominal'   => 1000000,
                        'detail'    => 'Per bulan (Gaji & Kehormatan Profesor)',
                    ],
                    [
                        'key'       => 'maal',
                        'jenis'     => 'Zakat Maal',
                        'frekuensi' => 'tahunan',
                        'nominal'   => 2500000,
                        'detail'    => 'Zakat atas simpanan & tabungan emas',
                    ],
                ],
            ],
            [
                'nama'              => 'Drs. Hendra Kusuma, M.Si.',
                'nik'               => '3278011005700003',
                'nip'               => '197005101998021003',
                'jenis_kelamin'     => 'Laki-laki',
                'tempat_lahir'      => 'Ciamis',
                'tanggal_lahir'     => '1970-05-10',
                'pekerjaan'         => 'Dosen Lektor',
                'alamat_lengkap'    => 'Jl. Sutisna Senjaya No. 88, Cibeureum, Kota Tasikmalaya',
                'email'             => 'hendrak@unsil.ac.id',
                'no_hp'             => '08111000003',
                'kategori'          => 'Dosen & Staf UNSIL',
                'unit_kerja'        => 'Fakultas Ilmu Sosial dan Ilmu Politik (FISIP) · Hukum Bisnis',
                'jenis_zakat'       => 'Zakat Penghasilan',
                'frekuensi'         => 'bulanan',
                'nominal'           => 450000,
                'metode_pembayaran' => 'transfer-bank',
                'pilihan_bank'      => 'BRI',
                'pilihan_ewallet'   => null,
                'kesepakatan_zakat' => [
                    [
                        'key'       => 'penghasilan',
                        'jenis'     => 'Zakat Penghasilan',
                        'frekuensi' => 'bulanan',
                        'nominal'   => 450000,
                        'detail'    => 'Per bulan',
                    ],
                ],
            ],
            [
                'nama'              => 'Ir. Budi Santoso, M.T.',
                'nik'               => '3278011511720004',
                'nip'               => '197211152000121004',
                'jenis_kelamin'     => 'Laki-laki',
                'tempat_lahir'      => 'Garut',
                'tanggal_lahir'     => '1972-11-15',
                'pekerjaan'         => 'Dosen Lektor',
                'alamat_lengkap'    => 'Jl. Siliwangi Perum Bumi Asri B-3, Tawang, Kota Tasikmalaya',
                'email'             => 'budisantoso@unsil.ac.id',
                'no_hp'             => '08111000004',
                'kategori'          => 'Dosen & Staf UNSIL',
                'unit_kerja'        => 'Fakultas Teknik · Teknik Sipil',
                'jenis_zakat'       => 'Zakat Penghasilan, Zakat Fitrah',
                'frekuensi'         => 'multi-frekuensi',
                'nominal'           => 725000,
                'metode_pembayaran' => 'e-wallet',
                'pilihan_bank'      => null,
                'pilihan_ewallet'   => 'QRIS',
                'kesepakatan_zakat' => [
                    [
                        'key'       => 'penghasilan',
                        'jenis'     => 'Zakat Penghasilan',
                        'frekuensi' => 'bulanan',
                        'nominal'   => 500000,
                        'detail'    => 'Per bulan',
                    ],
                    [
                        'key'              => 'fitrah',
                        'jenis'            => 'Zakat Fitrah',
                        'frekuensi'        => 'ramadan',
                        'jumlah_jiwa'      => 5,
                        'nominal_per_jiwa' => 45000,
                        'nominal'          => 225000,
                        'detail'           => '5 Jiwa × Rp 45.000',
                    ],
                ],
            ],
            [
                'nama'              => 'Dr. Dewi Lestari, M.Kes.',
                'nik'               => '3278026004810005',
                'nip'               => '198104202008012005',
                'jenis_kelamin'     => 'Perempuan',
                'tempat_lahir'      => 'Tasikmalaya',
                'tanggal_lahir'     => '1981-04-20',
                'pekerjaan'         => 'Dosen Lektor',
                'alamat_lengkap'    => 'Jl. Letjen Mashudi No. 102, Tamansari, Kota Tasikmalaya',
                'email'             => 'dewilestari@unsil.ac.id',
                'no_hp'             => '08111000005',
                'kategori'          => 'Dosen & Staf UNSIL',
                'unit_kerja'        => 'Fakultas Ilmu Kesehatan · Kesehatan Masyarakat',
                'jenis_zakat'       => 'Zakat Penghasilan, Zakat Maal',
                'frekuensi'         => 'multi-frekuensi',
                'nominal'           => 2000000,
                'metode_pembayaran' => 'transfer-bank',
                'pilihan_bank'      => 'BSI',
                'pilihan_ewallet'   => null,
                'kesepakatan_zakat' => [
                    [
                        'key'       => 'penghasilan',
                        'jenis'     => 'Zakat Penghasilan',
                        'frekuensi' => 'bulanan',
                        'nominal'   => 500000,
                        'detail'    => 'Per bulan',
                    ],
                    [
                        'key'       => 'maal',
                        'jenis'     => 'Zakat Maal',
                        'frekuensi' => 'tahunan',
                        'nominal'   => 1500000,
                        'detail'    => 'Zakat atas tabungan perbankan syariah',
                    ],
                ],
            ],
            [
                'nama'              => 'Dra. Ratna Wijaya, M.Pd.',
                'nik'               => '3278025809730006',
                'nip'               => '197309181999032006',
                'jenis_kelamin'     => 'Perempuan',
                'tempat_lahir'      => 'Sumedang',
                'tanggal_lahir'     => '1973-09-18',
                'pekerjaan'         => 'Dosen Lektor',
                'alamat_lengkap'    => 'Jl. RE Martadinata No. 55, Cipedes, Kota Tasikmalaya',
                'email'             => 'ratnaw@unsil.ac.id',
                'no_hp'             => '08111000006',
                'kategori'          => 'Dosen & Staf UNSIL',
                'unit_kerja'        => 'Fakultas Keguruan dan Ilmu Pendidikan (FKIP) · Pendidikan Bahasa Indonesia',
                'jenis_zakat'       => 'Zakat Penghasilan',
                'frekuensi'         => 'bulanan',
                'nominal'           => 400000,
                'metode_pembayaran' => 'transfer-bank',
                'pilihan_bank'      => 'BNI',
                'pilihan_ewallet'   => null,
                'kesepakatan_zakat' => [
                    [
                        'key'       => 'penghasilan',
                        'jenis'     => 'Zakat Penghasilan',
                        'frekuensi' => 'bulanan',
                        'nominal'   => 400000,
                        'detail'    => 'Per bulan',
                    ],
                ],
            ],
            [
                'nama'              => 'H. Supriadi, S.E., M.M.',
                'nik'               => '3278010502760007',
                'nip'               => '197602052003121007',
                'jenis_kelamin'     => 'Laki-laki',
                'tempat_lahir'      => 'Tasikmalaya',
                'tanggal_lahir'     => '1976-02-05',
                'pekerjaan'         => 'Dosen Lektor Kepala',
                'alamat_lengkap'    => 'Jl. Dr. Moch. Hatta No. 71, Cipedes, Kota Tasikmalaya',
                'email'             => 'supriadi@unsil.ac.id',
                'no_hp'             => '08111000007',
                'kategori'          => 'Dosen & Staf UNSIL',
                'unit_kerja'        => 'Fakultas Ekonomi dan Bisnis · Akuntansi',
                'jenis_zakat'       => 'Zakat Penghasilan, Zakat Maal, Zakat Fitrah',
                'frekuensi'         => 'multi-frekuensi',
                'nominal'           => 3680000,
                'metode_pembayaran' => 'transfer-bank',
                'pilihan_bank'      => 'Muamalat',
                'pilihan_ewallet'   => null,
                'kesepakatan_zakat' => [
                    [
                        'key'       => 'penghasilan',
                        'jenis'     => 'Zakat Penghasilan',
                        'frekuensi' => 'bulanan',
                        'nominal'   => 700000,
                        'detail'    => 'Per bulan',
                    ],
                    [
                        'key'       => 'maal',
                        'jenis'     => 'Zakat Maal',
                        'frekuensi' => 'tahunan',
                        'nominal'   => 2800000,
                        'detail'    => 'Zakat atas tabungan & investasi',
                    ],
                    [
                        'key'              => 'fitrah',
                        'jenis'            => 'Zakat Fitrah',
                        'frekuensi'        => 'ramadan',
                        'jumlah_jiwa'      => 4,
                        'nominal_per_jiwa' => 45000,
                        'nominal'          => 180000,
                        'detail'           => '4 Jiwa × Rp 45.000',
                    ],
                ],
            ],
            [
                'nama'              => 'Dr. Rina Marlina, M.Si.',
                'nik'               => '3278025407820008',
                'nip'               => '198207142009122008',
                'jenis_kelamin'     => 'Perempuan',
                'tempat_lahir'      => 'Bogor',
                'tanggal_lahir'     => '1982-07-14',
                'pekerjaan'         => 'Dosen Lektor',
                'alamat_lengkap'    => 'Perum Graha Persada No. 19, Kawalu, Kota Tasikmalaya',
                'email'             => 'rinamarlin@unsil.ac.id',
                'no_hp'             => '08111000008',
                'kategori'          => 'Dosen & Staf UNSIL',
                'unit_kerja'        => 'Fakultas Pertanian · Agroteknologi',
                'jenis_zakat'       => 'Zakat Penghasilan',
                'frekuensi'         => 'bulanan',
                'nominal'           => 450000,
                'metode_pembayaran' => 'e-wallet',
                'pilihan_bank'      => null,
                'pilihan_ewallet'   => 'GoPay',
                'kesepakatan_zakat' => [
                    [
                        'key'       => 'penghasilan',
                        'jenis'     => 'Zakat Penghasilan',
                        'frekuensi' => 'bulanan',
                        'nominal'   => 450000,
                        'detail'    => 'Per bulan',
                    ],
                ],
            ],
            [
                'nama'              => 'Dr. Indra Permana, M.Kom.',
                'nik'               => '3278013001850009',
                'nip'               => '198501302012121009',
                'jenis_kelamin'     => 'Laki-laki',
                'tempat_lahir'      => 'Tasikmalaya',
                'tanggal_lahir'     => '1985-01-30',
                'pekerjaan'         => 'Dosen Lektor',
                'alamat_lengkap'    => 'Jl. Tentara Pelajar No. 24, Empangsari, Tawang, Kota Tasikmalaya',
                'email'             => 'indrapermana@unsil.ac.id',
                'no_hp'             => '08111000009',
                'kategori'          => 'Dosen & Staf UNSIL',
                'unit_kerja'        => 'Fakultas Teknik · Informatika',
                'jenis_zakat'       => 'Zakat Penghasilan, Zakat Maal',
                'frekuensi'         => 'multi-frekuensi',
                'nominal'           => 2600000,
                'metode_pembayaran' => 'transfer-bank',
                'pilihan_bank'      => 'BSI',
                'pilihan_ewallet'   => null,
                'kesepakatan_zakat' => [
                    [
                        'key'       => 'penghasilan',
                        'jenis'     => 'Zakat Penghasilan',
                        'frekuensi' => 'bulanan',
                        'nominal'   => 600000,
                        'detail'    => 'Per bulan',
                    ],
                    [
                        'key'       => 'maal',
                        'jenis'     => 'Zakat Maal',
                        'frekuensi' => 'tahunan',
                        'nominal'   => 2000000,
                        'detail'    => 'Zakat aset dan simpanan',
                    ],
                ],
            ],
            [
                'nama'              => 'Hj. Sari Kusumadewi, S.Pd.',
                'nik'               => '3278025112800010',
                'nip'               => '198012112006042010',
                'jenis_kelamin'     => 'Perempuan',
                'tempat_lahir'      => 'Bandung',
                'tanggal_lahir'     => '1980-12-11',
                'pekerjaan'         => 'Tenaga Kependidikan / Staf',
                'alamat_lengkap'    => 'Jl. Sukalaya I No. 14, Cihideung, Kota Tasikmalaya',
                'email'             => 'sarikusu@unsil.ac.id',
                'no_hp'             => '08111000010',
                'kategori'          => 'Dosen & Staf UNSIL',
                'unit_kerja'        => 'Fakultas Keguruan dan Ilmu Pendidikan (FKIP) · Pendidikan Biologi',
                'jenis_zakat'       => 'Zakat Penghasilan, Zakat Fitrah',
                'frekuensi'         => 'multi-frekuensi',
                'nominal'           => 485000,
                'metode_pembayaran' => 'e-wallet',
                'pilihan_bank'      => null,
                'pilihan_ewallet'   => 'Dana',
                'kesepakatan_zakat' => [
                    [
                        'key'       => 'penghasilan',
                        'jenis'     => 'Zakat Penghasilan',
                        'frekuensi' => 'bulanan',
                        'nominal'   => 350000,
                        'detail'    => 'Per bulan',
                    ],
                    [
                        'key'              => 'fitrah',
                        'jenis'            => 'Zakat Fitrah',
                        'frekuensi'        => 'ramadan',
                        'jumlah_jiwa'      => 3,
                        'nominal_per_jiwa' => 45000,
                        'nominal'          => 135000,
                        'detail'           => '3 Jiwa × Rp 45.000',
                    ],
                ],
            ],
            [
                'nama'              => 'Prof. Bambang Wijaya, Ph.D.',
                'nik'               => '3278010304650011',
                'nip'               => '196504031990031011',
                'jenis_kelamin'     => 'Laki-laki',
                'tempat_lahir'      => 'Yogyakarta',
                'tanggal_lahir'     => '1965-04-03',
                'pekerjaan'         => 'Guru Besar / Dosen',
                'alamat_lengkap'    => 'Perumahan Mitra Batik Blok C-8, Indihiang, Kota Tasikmalaya',
                'email'             => 'bambangw@unsil.ac.id',
                'no_hp'             => '08111000011',
                'kategori'          => 'Dosen & Staf UNSIL',
                'unit_kerja'        => 'Fakultas Ekonomi dan Bisnis · Ekonomi Pembangunan',
                'jenis_zakat'       => 'Zakat Penghasilan, Zakat Maal',
                'frekuensi'         => 'multi-frekuensi',
                'nominal'           => 4200000,
                'metode_pembayaran' => 'transfer-bank',
                'pilihan_bank'      => 'Mandiri',
                'pilihan_ewallet'   => null,
                'kesepakatan_zakat' => [
                    [
                        'key'       => 'penghasilan',
                        'jenis'     => 'Zakat Penghasilan',
                        'frekuensi' => 'bulanan',
                        'nominal'   => 1200000,
                        'detail'    => 'Per bulan',
                    ],
                    [
                        'key'       => 'maal',
                        'jenis'     => 'Zakat Maal',
                        'frekuensi' => 'tahunan',
                        'nominal'   => 3000000,
                        'detail'    => 'Zakat simpanan deposito dan emas',
                    ],
                ],
            ],
            [
                'nama'              => 'Dra. Nani Suryani, M.Pd.',
                'nik'               => '3278026206740012',
                'nip'               => '197406222000032012',
                'jenis_kelamin'     => 'Perempuan',
                'tempat_lahir'      => 'Tasikmalaya',
                'tanggal_lahir'     => '1974-06-22',
                'pekerjaan'         => 'Dosen Lektor',
                'alamat_lengkap'    => 'Jl. Paseh No. 33, Tuguraja, Cihideung, Kota Tasikmalaya',
                'email'             => 'nanisury@unsil.ac.id',
                'no_hp'             => '08111000012',
                'kategori'          => 'Dosen & Staf UNSIL',
                'unit_kerja'        => 'Fakultas Keguruan dan Ilmu Pendidikan (FKIP) · Pendidikan Sejarah',
                'jenis_zakat'       => 'Zakat Penghasilan',
                'frekuensi'         => 'bulanan',
                'nominal'           => 400000,
                'metode_pembayaran' => 'transfer-bank',
                'pilihan_bank'      => 'BSI',
                'pilihan_ewallet'   => null,
                'kesepakatan_zakat' => [
                    [
                        'key'       => 'penghasilan',
                        'jenis'     => 'Zakat Penghasilan',
                        'frekuensi' => 'bulanan',
                        'nominal'   => 400000,
                        'detail'    => 'Per bulan',
                    ],
                ],
            ],

            // =========================================================================
            // 2. MUZAKKI MASYARAKAT UMUM (DENGAN KESEPAKATAN ZAKAT REALISTIS)
            // =========================================================================
            [
                'nama'              => 'H. Dani Firmansyah, S.T.',
                'nik'               => '3278011909880001',
                'nip'               => null,
                'jenis_kelamin'     => 'Laki-laki',
                'tempat_lahir'      => 'Tasikmalaya',
                'tanggal_lahir'     => '1988-09-19',
                'pekerjaan'         => 'Pengusaha Konstruksi',
                'alamat_lengkap'    => 'Jl. Ir. H. Juanda No. 88, Panyingkiran, Indihiang, Kota Tasikmalaya',
                'email'             => 'danifirmansyah@outlook.com',
                'no_hp'             => '08222000001',
                'kategori'          => 'Muzakki Umum',
                'unit_kerja'        => 'Masyarakat Umum',
                'jenis_zakat'       => 'Zakat Penghasilan, Zakat Maal, Zakat Fitrah',
                'frekuensi'         => 'multi-frekuensi',
                'nominal'           => 6180000,
                'metode_pembayaran' => 'transfer-bank',
                'pilihan_bank'      => 'BSI',
                'pilihan_ewallet'   => null,
                'kesepakatan_zakat' => [
                    [
                        'key'       => 'penghasilan',
                        'jenis'     => 'Zakat Penghasilan',
                        'frekuensi' => 'bulanan',
                        'nominal'   => 1000000,
                        'detail'    => 'Per bulan',
                    ],
                    [
                        'key'       => 'maal',
                        'jenis'     => 'Zakat Maal',
                        'frekuensi' => 'tahunan',
                        'nominal'   => 5000000,
                        'detail'    => 'Zakat simpanan modal & tabungan',
                    ],
                    [
                        'key'              => 'fitrah',
                        'jenis'            => 'Zakat Fitrah',
                        'frekuensi'        => 'ramadan',
                        'jumlah_jiwa'      => 4,
                        'nominal_per_jiwa' => 45000,
                        'nominal'          => 180000,
                        'detail'           => '4 Jiwa × Rp 45.000',
                    ],
                ],
            ],
            [
                'nama'              => 'Hj. Siti Mariam',
                'nik'               => '3278024503790002',
                'nip'               => null,
                'jenis_kelamin'     => 'Perempuan',
                'tempat_lahir'      => 'Tasikmalaya',
                'tanggal_lahir'     => '1979-03-05',
                'pekerjaan'         => 'Wiraswasta / Pemilik Toko',
                'alamat_lengkap'    => 'Jl. Pasar Wetan No. 15, Cihideung, Kota Tasikmalaya',
                'email'             => 'sitimariam.toko@gmail.com',
                'no_hp'             => '08222000002',
                'kategori'          => 'Muzakki Umum',
                'unit_kerja'        => 'Masyarakat Umum',
                'jenis_zakat'       => 'Zakat Maal, Zakat Fitrah',
                'frekuensi'         => 'multi-frekuensi',
                'nominal'           => 2225000,
                'metode_pembayaran' => 'e-wallet',
                'pilihan_bank'      => null,
                'pilihan_ewallet'   => 'QRIS',
                'kesepakatan_zakat' => [
                    [
                        'key'       => 'maal',
                        'jenis'     => 'Zakat Maal',
                        'frekuensi' => 'tahunan',
                        'nominal'   => 2000000,
                        'detail'    => 'Zakat perniagaan dan simpanan emas',
                    ],
                    [
                        'key'              => 'fitrah',
                        'jenis'            => 'Zakat Fitrah',
                        'frekuensi'        => 'ramadan',
                        'jumlah_jiwa'      => 5,
                        'nominal_per_jiwa' => 45000,
                        'nominal'          => 225000,
                        'detail'           => '5 Jiwa × Rp 45.000',
                    ],
                ],
            ],
            [
                'nama'              => 'Ahmad Ridwan, S.Kom.',
                'nik'               => '3278012010900003',
                'nip'               => null,
                'jenis_kelamin'     => 'Laki-laki',
                'tempat_lahir'      => 'Bandung',
                'tanggal_lahir'     => '1990-10-20',
                'pekerjaan'         => 'Software Engineer',
                'alamat_lengkap'    => 'Jl. Cisalak No. 44, Sukamanah, Cipedes, Kota Tasikmalaya',
                'email'             => 'ahmad.ridwan.dev@gmail.com',
                'no_hp'             => '08222000003',
                'kategori'          => 'Muzakki Umum',
                'unit_kerja'        => 'Masyarakat Umum',
                'jenis_zakat'       => 'Zakat Penghasilan',
                'frekuensi'         => 'bulanan',
                'nominal'           => 500000,
                'metode_pembayaran' => 'e-wallet',
                'pilihan_bank'      => null,
                'pilihan_ewallet'   => 'ShopeePay',
                'kesepakatan_zakat' => [
                    [
                        'key'       => 'penghasilan',
                        'jenis'     => 'Zakat Penghasilan',
                        'frekuensi' => 'bulanan',
                        'nominal'   => 500000,
                        'detail'    => 'Per bulan (Gaji remote work)',
                    ],
                ],
            ],
            [
                'nama'              => 'Yeni Susilawati, S.E.',
                'nik'               => '3278036011920004',
                'nip'               => null,
                'jenis_kelamin'     => 'Perempuan',
                'tempat_lahir'      => 'Garut',
                'tanggal_lahir'     => '1992-11-20',
                'pekerjaan'         => 'Pegawai BUMN',
                'alamat_lengkap'    => 'Perum Bumi Resik Panglayungan Blok D-15, Cipedes, Kota Tasikmalaya',
                'email'             => 'yenisus@gmail.com',
                'no_hp'             => '08222000004',
                'kategori'          => 'Muzakki Umum',
                'unit_kerja'        => 'Masyarakat Umum',
                'jenis_zakat'       => 'Zakat Penghasilan, Zakat Fitrah',
                'frekuensi'         => 'multi-frekuensi',
                'nominal'           => 435000,
                'metode_pembayaran' => 'transfer-bank',
                'pilihan_bank'      => 'Mandiri',
                'pilihan_ewallet'   => null,
                'kesepakatan_zakat' => [
                    [
                        'key'       => 'penghasilan',
                        'jenis'     => 'Zakat Penghasilan',
                        'frekuensi' => 'bulanan',
                        'nominal'   => 300000,
                        'detail'    => 'Per bulan',
                    ],
                    [
                        'key'              => 'fitrah',
                        'jenis'            => 'Zakat Fitrah',
                        'frekuensi'        => 'ramadan',
                        'jumlah_jiwa'      => 3,
                        'nominal_per_jiwa' => 45000,
                        'nominal'          => 135000,
                        'detail'           => '3 Jiwa × Rp 45.000',
                    ],
                ],
            ],
        ];

        foreach ($muzakkiData as $data) {
            Muzakki::updateOrCreate(
                ['nama' => $data['nama']],
                $data
            );
        }
    }
}
